//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface PersonDto {
    id: number;
    name?: string | undefined;
    age: number;
    country?: string | undefined;
}

export interface WeatherForecastDto {
    date: Date;
    temperatureC: number;
    temperatureF: number;
    summary?: string | undefined;
}