//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface PatientDto {
    id: string;
    fullName: string;
    age: number;
    dateOfBirth: Date;
    pesel: string;
}

export interface PostPatientDto {
    fullName: string;
    dateOfBirth: Date;
    pesel: string;
    address: PostAddressDto;
    doctorId: string;
    departmentId: string;
    roomId: string;
}

export interface PostAddressDto {
    country: string;
    city: string;
    street: string;
    homeNumber: string;
}

export interface AddressDto {
    id: string;
    country: string;
    city: string;
    street: string;
    homeNumber: string;
}

export interface CommentDto {
    id: string;
    message: string;
    createdDate: Date;
    updatedDate?: Date | undefined;
}

export interface PostCommentDto {
    message: string;
    createdDate: Date;
    updatedDate?: Date | undefined;
    patientId: string;
    doctorId: string;
}

export interface ContactDto {
    id: string;
    mobilePhone: string;
    email: string;
}

export interface PostContactDto {
    mobilePhone?: string | undefined;
    email?: string | undefined;
    patientId: string;
}

export interface DepartmentDto {
    id: string;
    value: string;
}

export interface PostDepartmentDto {
    value: string;
}

export interface DoctorDto {
    id: string;
    fullName: string;
}

export interface PostDoctorDto {
    fullName: string;
}

export interface RoomDto {
    id: string;
    number: number;
}

export interface PostRoomDto {
    number: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}